name: 🐞 Bug
description: Report an issue to help improve the project.
labels: ["bug"]
body:
  - type: markdown
    id: 
    attributes:
      value: |
        **Your issue may already be reported!**
        **Please search on the issues tab before creating one.**
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the issue, also include what you tried and what didn't work! If possible upload a screenshot.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: Tell us how it should work
    validations:
      required: false
  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: Explain the difference of expected Behavior from current behaviour 
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false
  - type: markdown
    id: environ-version
    attributes:
      value: |
        ## Your Environment
        <!--- Include as many relevant details about the environment you experienced the bug in -->
        * Version used:
        * Browser Name and version:
        * Operating System and version (desktop and/or mobile):
        * Link to your project:
  - type: markdown
    attributes:
      value: |
       ## Thanks for taking the time to add a issue!
        To claim this issue, please ask for it below. 
        The maintainers will assign a contributor to this issue.
