name: Add contributors
on:
  # schedule:
  #   - cron:  '20 20 * * *'
  push:
    branches:
      - master

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run-name: Changes to Readme - ${{ inputs.deploy_target }} by @${{ github.actor }})
      with:
        CONTRIBUTOR: 'https://github.com/ComputerSocietyVITC/Annual-Yearbook/graphs/contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'